apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chat-widget
data:
  MONGODB_URI: "mongodb+srv://sab:sab@cluster0.buzlvja.mongodb.net/chat-widget"
  PORT: "5000"
  NODE_ENV: "production"
  VITE_API_URL: "http://13.232.3.204/api"
  VITE_WEBSOCKET_URL: "ws://13.232.3.204"
